In [1]:
from cymetric import timeseries as com
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.material is not yet QA compliant.
  return f(*args, **kwds)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: QAWarning: pyne.enrichment is not yet QA compliant.
  return f(*args, **kwds)

In [2]:
import cymetric as cym
db = cym.dbopen('cyclus.sqlite')
ev = cym.Evaluator(db=db, write=False)

In [3]:
from cymetric import graphs

In [4]:
cym.graphs.flow_graph(ev)

In [5]:
from cymetric import timeseries as tim

In [6]:
uox = tim.transactions(ev, senders=['storage_uox_spent'])
uox[(uox.Mass != 0)]

Empty DataFrame
Columns: [Time, Mass]
Index: []

In [11]:
uox_spent = tim.transactions(ev, commodities=['c_uox'])
uox_u5_spent = tim.transactions(ev, commodities=['c_uox'], nucs=['235U'])
uox_u5_spent['Mass'] = uox_u5_spent['Mass']
uox_u5_spent['Mass'].dropna()

0          0.000000
1          0.000000
2       5313.027634
3       2951.773739
4       2951.773739
5       2951.773739
6       2951.773739
7       2951.773739
8       3935.698319
9       2951.773739
10      2951.773739
11      2951.773739
12      2951.773739
13      2951.773739
14      3935.698319
15      2951.773739
16      2951.773739
17      2951.773739
18      2951.773739
19      2951.773739
20      3935.698319
21      2951.773739
22      2951.773739
23      2951.773739
24      2951.773739
25      2951.773739
26      3935.698319
27      2951.773739
28      2951.773739
29      2951.773739
           ...
1770    2951.773739
1771    3935.698319
1772    2951.773739
1773    2951.773739
1774    2951.773739
1775    2951.773739
1776    2951.773739
1777    3935.698319
1778    2951.773739
1779    2951.773739
1780    2951.773739
1781    2951.773739
1782    2951.773739
1783    3935.698319
1784    2951.773739
1785    2951.773739
1786    2951.773739
1787    2951.773739
1788    2951.773739
1789    3935.698319
1790    2951.773739
1791    2951.773739
1792    2951.773739
1793    2951.773739
1794    2951.773739
1795    3935.698319
1796    2951.773739
1797    2951.773739
1798    2951.773739
1799    2951.773739
Name: Mass, Length: 1800, dtype: float64

In [8]:
uox[(uox.Mass != 0)]

Empty DataFrame
Columns: [Time, Mass]
Index: []

In [9]:
powe = tim.get_power(ev)
#powe[(powe.Value != 0)]
powe

/Users/mouginot/.local/lib/python3.5/site-packages/cymetric/timeseries.py:226: UserWarning: no faciity provided
  warnings.warn(wng_msg, UserWarning)

      Time   Value
0        0     0.0
1        1     0.0
2        2     0.0
3        3  1200.0
4        4  1200.0
5        5  1200.0
6        6  1200.0
7        7  1200.0
8        8     0.0
9        9  1200.0
10      10  1200.0
11      11  1200.0
12      12  1200.0
13      13  1200.0
14      14     0.0
15      15  1200.0
16      16  1200.0
17      17  1200.0
18      18  1200.0
19      19  1200.0
20      20     0.0
21      21  1200.0
22      22  1200.0
23      23  1200.0
24      24  1200.0
25      25  1200.0
26      26     0.0
27      27  1200.0
28      28  1200.0
29      29  1200.0
...    ...     ...
1770  1770  1200.0
1771  1771     0.0
1772  1772  1200.0
1773  1773  1200.0
1774  1774  1200.0
1775  1775  1200.0
1776  1776  1200.0
1777  1777     0.0
1778  1778  1200.0
1779  1779  1200.0
1780  1780  1200.0
1781  1781  1200.0
1782  1782  1200.0
1783  1783     0.0
1784  1784  1200.0
1785  1785  1200.0
1786  1786  1200.0
1787  1787  1200.0
1788  1788  1200.0
1789  1789     0.0
1790  1790  1200.0
1791  1791  1200.0
1792  1792  1200.0
1793  1793  1200.0
1794  1794  1200.0
1795  1795     0.0
1796  1796  1200.0
1797  1797  1200.0
1798  1798  1200.0
1799  1799  1200.0

[1800 rows x 2 columns]